Features/output
Grasseh/PFE_H_2019 pull request #19
Opened 2019-02-23 00:24 UTC by Stalfy

2019-02-24 17:37 UTC, KB07 reviewed
seems good to me

2019-02-24 17:38 UTC, KB07 approved these changes

2019-02-26 14:58 UTC, doomy23 approved these changes
Good job!
J'aime l'idée des template d'outputs!!!
Ça donne du contrôle à l'utilisateur en plus sur la sortie!!!

2019-02-26 14:59 UTC, Grasseh commented
Somehow ton dernier "merging staging into this" a fuck up ta PR. Si tu regarde les files changed, t'As remove beaucoup de commits de d'autre monde.

2019-02-26 15:06 UTC, Grasseh requested changes
Y'a des conflits à régler et somehow y'a beaucoup de files que ton PR delete!

2019-02-26 20:47 UTC, Grasseh approved these changes
OTS LGTM
Although assocs > maps

2019-02-26 20:49 UTC, Stalfy commented
Travis bug, letting @Grasseh  merge

2019-02-26 20:49 UTC, merged