Load paths from config file
Grasseh/PFE_H_2019 pull request #26
Opened 2019-03-09 17:14 UTC by Grasseh

Also allow to pass config file either default or from args.

2019-03-09 18:16 UTC, KB07 approved these changes
Seems good to me

2019-03-10 18:15 UTC, Lolskate approved these changes
Clean and thorough 👍

2019-03-11 15:42 UTC, Stalfy requested changes

2019-03-11 15:42 UTC, Stalfy commented on demo/js/markdown/test1.md
> +[*module](../testFacade.js)
This does not reflect the new syntax used in markdown files.

2019-03-11 15:42 UTC, Stalfy commented on demo/js/markdown/output/output.html
> +<p><a href="NodeInvoker"><em>invoker</a>
These 2 lines with be removed with @Lolskate PR, most likely to get a conflict.

2019-03-11 15:43 UTC, Stalfy commented on demo/js/markdown/output/output.html
> +<p><a href="NodeInvoker"><em>invoker</a>
Line 7 and 8 spicifically.

2019-03-11 23:20 UTC, Stalfy requested changes
Nitpick : Extract acceptance tests in their own folder.

2019-03-12 19:17 UTC, Stalfy approved these changes

2019-03-12 19:17 UTC, merged