Features/docs + Bin file
Grasseh/PFE_H_2019 pull request #29
Opened 2019-03-18 08:36 UTC by doomy23

J'ai commencé quelque chose pour la doc et je trouvais important que le cadriciel puisse être exécuter comme un client par les autres projets (d'ou le bin/cli,js)

Si vous avez plus d'idées ou que vous préféreriez que ce soit séparrer en plusieurs fichiers MD avec un index etc. Je peux faire ça aussi.
Exemple : README.md / CONTRIBUTING.md / Getting-started.md ?

J'attend votre feedback.

2019-03-19 17:13 UTC, Grasseh commented on LICENSE
> +
Lacks a 

Copyright (c) 2019-2019, Team Name and or members + email

2019-03-19 17:15 UTC, Grasseh requested changes
Bin Name should not be cli.js but the name of the package.

In this case it should either be bin/pfe or bin/whatevernameonthepoll

Not it should NOT have the js extension.

2019-03-19 17:15 UTC, Grasseh commented on LICENSE
> +
Lacks a

Copyright (c) 2019-2019, Team Name and or members + email

2019-03-22 14:22 UTC, Grasseh approved these changes

2019-03-23 17:58 UTC, KB07 approved these changes
Seems good to me.

2019-03-23 18:51 UTC, merged